version: "2"
services:
  jupyter:
    build: .
    ports:
      - "8000:8000"
    networks: 
      - jupyter
  sinlegeuser:
    image: jupyterhub/singleuser
    networks: 
      - jupyter
networks:
  jupyter:
    driver: bridge
